import Link from "next/link";
import { ArrowRight, ChevronDown, Info, Video } from "lucide-react";
import { getCurrentSession } from "@/lib/auth-session";
import { getProductUsageVideos } from "@/lib/usage-video-api";
import { UsageVideoCard } from "./usage-video-card";
import { UsageVideoForm } from "./usage-video-form";

export async function ProductUsageVideos({ productId }: { productId: string }) {
  const [user, result] = await Promise.all([getCurrentSession(), getProductUsageVideos(productId, 0, 3).then((data) => ({ data, error: false })).catch(() => ({ data: null, error: true }))]);
  const returnTo = `/products/${encodeURIComponent(productId)}/usage-videos`;
  return <section id="usage-videos" className="mt-6 scroll-mt-28 rounded-[20px] border border-[#eadde1] bg-white p-5">
    <header className="mb-4 flex items-start justify-between gap-4"><div className="min-w-0"><p className="mb-1.5 text-[10px] font-bold tracking-[.14em] text-[#ad4f70]">HOW TO USE</p><h2 className="flex items-center gap-2 font-myeongjo text-xl font-semibold"><Video size={18} className="text-[#b85b79]" /> 영상으로 보는 사용법</h2><p className="mt-1 text-xs leading-5 text-[#86777d]">사용자가 직접 소개하는 사용 팁과 채널을 확인해요.</p></div>{result.data && result.data.totalElements > 0 && <Link href={returnTo} className="inline-flex min-h-10 shrink-0 items-center gap-1 text-xs font-semibold text-[#a44c6a]">전체보기 ({result.data.totalElements}) <ArrowRight size={14} /></Link>}</header>
    {result.error ? <p role="status" className="rounded-xl border border-[#eadde1] px-4 py-4 text-xs leading-5 text-[#8a727b]">사용법 영상을 불러오지 못했어요. 잠시 후 다시 확인해 주세요.</p> : result.data?.content.length ? <div className="grid gap-3">{result.data.content.map((video) => <UsageVideoCard key={video.id} video={video} />)}</div> : <div className="flex items-center gap-3 rounded-xl border border-dashed border-[#dfd2d6] px-4 py-4"><Video size={19} className="shrink-0 text-[#c57b94]" /><div><p className="text-sm font-semibold text-[#6f5c64]">첫 사용법 영상을 기다리고 있어요</p><p className="mt-0.5 text-xs leading-5 text-[#927f87]">직접 만든 영상으로 사용 팁과 채널을 소개해 보세요.</p></div></div>}
    <div className="mt-4 border-t border-[#eee5e8] pt-3">{user ? <details className="group"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-3 text-sm font-semibold text-[#a44c6a]">내 유튜브 사용법 영상 등록하기 <ChevronDown size={16} className="transition group-open:rotate-180" /></summary><div className="pb-2 pt-3"><UsageVideoForm productId={productId} /></div></details> : <Link href={`/login?returnTo=${encodeURIComponent(returnTo)}`} className="inline-flex min-h-11 items-center gap-1 text-xs font-semibold text-[#a44c6a] underline decoration-[#d9a4b5] underline-offset-4">로그인하고 내 영상 등록하기 <ArrowRight size={14} /></Link>}{user && <Link href="/my/usage-videos" className="inline-flex min-h-10 items-center text-xs text-[#85747b] underline underline-offset-4">내가 등록한 영상 · 검토 상태 관리</Link>}</div>
    <details className="group border-t border-[#eee5e8] pt-1"><summary className="flex min-h-10 cursor-pointer list-none items-center justify-between gap-3 text-[11px] font-semibold text-[#817178]"><span className="flex items-center gap-1.5"><Info size={13} /> 영상 등록·노출 안내</span><ChevronDown size={14} className="transition group-open:rotate-180" /></summary><div className="pb-1 text-[10px] leading-5 text-[#95858b]"><p>사용자가 등록한 영상 중 관리자 승인을 마친 영상만 공개돼요.</p><p className="mt-1">등록자가 제공한 채널 정보이며 채널 소유권 인증을 의미하지 않아요. 노출 승인은 제품의 효능이나 영상 내용을 보증하지 않아요.</p></div></details>
  </section>;
}
