import Link from "next/link";
import { ArrowLeft, Award, Heart, MessageCircle, Sparkles } from "lucide-react";
import { ExpertAvatar, ExpertDisclaimer, expertTopics } from "@/components/expert-ui";
import { getExpertRanking } from "@/lib/api";

const periods = [{ code: "WEEK", name: "이번 주" }, { code: "MONTH", name: "이번 달" }, { code: "YEAR", name: "올해" }, { code: "ALL_TIME", name: "전체" }];

export default async function ExpertRankingPage({ searchParams }: { searchParams: Promise<{ period?: string; topic?: string }> }) {
  const params = await searchParams;
  const period = periods.some((item) => item.code === params.period) ? params.period! : "MONTH";
  const topic = expertTopics.some((item) => item.code === params.topic) ? params.topic : undefined;
  const ranking = await getExpertRanking(period, topic);
  const href = (nextPeriod: string, nextTopic?: string) => `/experts/ranking?period=${nextPeriod}${nextTopic ? `&topic=${nextTopic}` : ""}`;
  return <div className="min-h-screen pb-24"><section className="border-b border-[#ecd0d7] bg-[#fff3f6] py-10 md:py-16"><div className="container-page"><Link href="/experts" className="inline-flex min-h-11 items-center gap-2 text-sm text-[#78666c]"><ArrowLeft size={16} /> 전문가 홈</Link><div className="mt-4 flex items-end gap-3"><Award className="text-[#a55267]" size={34} /><div><p className="eyebrow mb-1">ACTIVITY RANKING</p><h1 className="font-myeongjo text-4xl font-bold">전문가 활동 랭킹</h1></div></div><p className="mt-4 max-w-2xl text-sm leading-7 text-[#74646a]">화력 안에서 질문에 답하고 유용한 정보를 나눈 활동을 기간별로 모았습니다.</p></div></section><section className="container-page py-9"><div className="scrollbar-hide flex gap-2 overflow-x-auto pb-2">{periods.map((item) => <Link key={item.code} href={href(item.code, topic)} className={`shrink-0 rounded-full px-4 py-2.5 text-xs font-bold ${period === item.code ? "bg-[#3e3236] text-white" : "border border-[#dfbdc5] bg-white text-[#746268]"}`}>{item.name}</Link>)}</div><div className="scrollbar-hide mt-3 flex gap-2 overflow-x-auto pb-2"><Link href={href(period)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${!topic ? "bg-[#f3ced8] text-[#91465a]" : "bg-white text-[#7f6b72]"}`}>전체 주제</Link>{expertTopics.map((item) => <Link key={item.code} href={href(period, item.code)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${topic === item.code ? "bg-[#f3ced8] text-[#91465a]" : "bg-white text-[#7f6b72]"}`}>{item.name}</Link>)}</div><div className="mt-7 space-y-4">{ranking.content.map((item) => <Link key={item.expert.id} href={`/experts/${item.expert.slug}`} className="paper-card grid gap-4 rounded-[24px] p-5 sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className={`grid h-10 w-10 place-items-center rounded-full font-myeongjo text-lg font-bold ${item.rank <= 3 ? "bg-[#a55368] text-white" : "bg-[#f4e7ea] text-[#80636b]"}`}>{item.rank}</span><div className="flex min-w-0 items-center gap-3"><ExpertAvatar expert={item.expert} /><div><h2 className="font-myeongjo text-lg font-bold">{item.expert.realName}</h2><p className="mt-1 text-xs text-[#826e75]">{item.expert.specialty ?? "의사"} · {item.expert.verificationLabel}</p></div></div><div className="flex gap-4 border-t border-[#ead9dd] pt-3 text-center text-[10px] text-[#846f76] sm:border-l sm:border-t-0 sm:pl-5 sm:pt-0"><span><MessageCircle className="mx-auto mb-1" size={15} /><b className="text-sm text-[#493c40]">{item.periodStats.answerCount}</b><br />답변</span><span><Heart className="mx-auto mb-1" size={15} /><b className="text-sm text-[#493c40]">{item.periodStats.helpfulCount}</b><br />도움</span><span><Sparkles className="mx-auto mb-1" size={15} /><b className="text-sm text-[#493c40]">{item.activityScore}</b><br />활동점수</span></div></Link>)}</div><div className="mt-8"><ExpertDisclaimer /></div></section></div>;
}
